INSERT INTO personagem (nome, nacionalidade, classe, avatar)
VALUES
    ('Jett', 'COREIA DO SUL', 'DUELISTA', 'assets/avatars/jett.png'),
    ('Viper', 'ESTADOS UNIDOS', 'CONTROLADOR', 'assets/avatars/viper.png'),
    ('Brimstone', 'ESTADOS UNIDOS', 'CONTROLADOR', 'assets/avatars/brimstone.png'),
    ('Omen', 'DESCONHECIDA', 'CONTROLADOR', 'assets/avatars/omen.png'),
    ('Killjoy', 'ALEMANHA', 'SENTINELA', 'assets/avatars/killjoy.png'),
    ('Cypher', 'MARROCOS', 'SENTINELA', 'assets/avatars/cypher.png'),
    ('Sova', 'RÚSSIA', 'INICIADOR', 'assets/avatars/sova.png'),
    ('Breach', 'SUÉCIA', 'INICIADOR', 'assets/avatars/breach.png'),
    ('Skye', 'AUSTRÁLIA', 'INICIADOR', 'assets/avatars/skye.png'),
    ('Reyna', 'MÉXICO', 'DUELISTA', 'assets/avatars/reyna.png'),
    ('Phoenix', 'REINO UNIDO', 'DUELISTA', 'assets/avatars/phoenix.png'),
    ('Yoru', 'JAPÃO', 'DUELISTA', 'assets/avatars/yoru.png'),
    ('Gekko', 'ESTADOS UNIDOS', 'INICIADOR', 'assets/avatars/gekko.png'),
    ('Fade', 'TURQUIA', 'INICIADOR', 'assets/avatars/fade.png'),
    ('Raze', 'BRASIL', 'DUELISTA', 'assets/avatars/raze.png'),
    ('Chamber', 'FRANÇA', 'SENTINELA', 'assets/avatars/chamber.png'),
    ('KAY/O', 'DESCONHECIDA', 'SENTINELA', 'assets/avatars/kayo.png'),
    ('Harbor', 'INDIA', 'CONTROLADOR', 'assets/avatars/harbor.png'),
    ('Astra', 'GANA', 'CONTROLADOR', 'assets/avatars/astra.png'),
    ('Neon', 'FILIPINAS', 'DUELISTA', 'assets/avatars/neon.png'),
    ('Sage', 'CHINA', 'SENTINELA', 'assets/avatars/sage.png');

INSERT INTO detalhes_personagem (nome, descricao, fk_personagem_id) VALUES
('Jett', 'Representando a Coreia do Sul, sua terra natal, Jett tem um estilo de luta ágil e evasivo que permite que ela assuma riscos como ninguém. Ela corre em meio a qualquer confronto, cortando os inimigos antes mesmo que eles percebam quem ou o que os atingiu.', (SELECT id FROM personagem WHERE nome = 'Jett')),
('Viper', 'Viper, a química dos Estados Unidos, emprega uma variedade de dispositivos químicos venenosos para controlar o campo de batalha e prejudicar a visão do inimigo. Se as toxinas não matarem a presa, seus jogos mentais certamente o farão.', (SELECT id FROM personagem WHERE nome = 'Viper')),
('Brimstone', 'Vindo diretamente dos EUA, o arsenal orbital de Brimstone garante que o esquadrão dele esteja sempre em vantagem. Sua capacidade de oferecer utilidade com precisão a distância faz dele um comandante inigualável na linha de frente. ', (SELECT id FROM personagem WHERE nome = 'Brimstone')),
('Omen', 'Omen, uma lembrança fantasmagórica, caça nas sombras. Ele cega os inimigos, teleporta-se pelo campo e deixa a paranoia assumir o controle enquanto o adversário tenta descobrir de onde virá seu próximo ataque.', (SELECT id FROM personagem WHERE nome = 'Omen')),
('Killjoy', 'Killjoy, uma alemã genial, defende posições-chave no campo de batalha com uma coleção de armadilhas, torretas e minas. Cada invenção foi desenvolvida para punir qualquer atacante burro o suficiente para não bater em retirada.', (SELECT id FROM personagem WHERE nome = 'Killjoy')),
('Cypher', 'Cypher, um vendedor de informações do Marrocos, é uma verdadeira rede de vigilância de um homem só que fica de olho em cada movimento dos inimigos. Nenhum segredo está a salvo. Nenhuma manobra passa despercebida. Cypher está sempre vigiando.', (SELECT id FROM personagem WHERE nome = 'Cypher')),
('Sova', 'Nascido sob o eterno inverno das tundras russas, Sova rastreia, encontra e elimina inimigos com eficiência e precisão implacáveis. Seu arco personalizado e suas habilidades inigualáveis de reconhecimento garantem que nenhuma presa escape.', (SELECT id FROM personagem WHERE nome = 'Sova')),
('Breach', 'Breach, o homem-biônico sueco, dispara poderosos jatos cinéticos para forçar a abertura de um caminho pelo território inimigo. O dano e a interrupção que ele causa garantem que nenhuma luta seja justa.', (SELECT id FROM personagem WHERE nome = 'Breach')),
('Skye', 'Mandando um salve direto da Austrália, Skye e sua equipe de feras desbravam territórios hostis. Com seus poderes de cura e suas criações que partem pra cima dos inimigos, qualquer equipe ficará mais forte e mais segura tendo Skye como aliada.', (SELECT id FROM personagem WHERE nome = 'Skye')),
('Reyna', 'Criada no coração do México, Reyna domina o combate individual, destacando-se a cada abate efetuado. Sua capacidade só é limitada por sua própria perícia, tornando-a bastante dependente de desempenho.', (SELECT id FROM personagem WHERE nome = 'Reyna')),
('Phoenix', 'Chegando com tudo diretamente do Reino Unido, o poder estelar de Phoenix reluz em seu estilo de luta, incendiando o campo de batalha com luz e estilo. Tendo ajuda ou não, ele entra na luta como e quando achar que deve.', (SELECT id FROM personagem WHERE nome = 'Phoenix')),
('Yoru', 'Yoru, o agente de duelo japonês, utiliza sua habilidade dimensional única para desaparecer do campo de batalha e emboscar inimigos desprevenidos. Ele se diverte deixando os adversários confusos e caçando presas desprevenidas.', (SELECT id FROM personagem WHERE nome = 'Yoru')),
('Astra', 'Astra, a controladora de Gana, manipula energia cósmica para dobrar a própria vontade. Com a habilidade de mudar completamente o campo de batalha, ela está sempre um passo à frente dos inimigos.', (SELECT id FROM personagem WHERE nome = 'Astra')),
('KAY/O', 'KAY/O, o duelo de combate robótico, é um verdadeiro terror para os radianitas. Com a capacidade de lançar granadas de fragmentação, suprimir habilidades e até mesmo se autodestruir para garantir eliminações, Kay/o é uma força a ser reconhecida.', (SELECT id FROM personagem WHERE nome = 'KAY/O'));